/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as RumRouteImport } from './routes/rum'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatistikIndexRouteImport } from './routes/statistik/index'
import { Route as RumIndexRouteImport } from './routes/rum/index'
import { Route as KatalogIndexRouteImport } from './routes/katalog/index'
import { Route as StatistikTabRouteImport } from './routes/statistik/$tab'
import { Route as RumRoomIdRouteImport } from './routes/rum/$roomId'
import { Route as KatalogKindTypeIdRouteImport } from './routes/katalog/$kind.$typeId'

const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const RumRoute = RumRouteImport.update({
  id: '/rum',
  path: '/rum',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikIndexRoute = StatistikIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatistikRoute,
} as any)
const RumIndexRoute = RumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RumRoute,
} as any)
const KatalogIndexRoute = KatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KatalogRoute,
} as any)
const StatistikTabRoute = StatistikTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => StatistikRoute,
} as any)
const RumRoomIdRoute = RumRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RumRoute,
} as any)
const KatalogKindTypeIdRoute = KatalogKindTypeIdRouteImport.update({
  id: '/$kind/$typeId',
  path: '/$kind/$typeId',
  getParentRoute: () => KatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/katalog': typeof KatalogRouteWithChildren
  '/profil': typeof ProfilRoute
  '/rum': typeof RumRouteWithChildren
  '/statistik': typeof StatistikRouteWithChildren
  '/rum/$roomId': typeof RumRoomIdRoute
  '/statistik/$tab': typeof StatistikTabRoute
  '/katalog/': typeof KatalogIndexRoute
  '/rum/': typeof RumIndexRoute
  '/statistik/': typeof StatistikIndexRoute
  '/katalog/$kind/$typeId': typeof KatalogKindTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/profil': typeof ProfilRoute
  '/rum/$roomId': typeof RumRoomIdRoute
  '/statistik/$tab': typeof StatistikTabRoute
  '/katalog': typeof KatalogIndexRoute
  '/rum': typeof RumIndexRoute
  '/statistik': typeof StatistikIndexRoute
  '/katalog/$kind/$typeId': typeof KatalogKindTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/katalog': typeof KatalogRouteWithChildren
  '/profil': typeof ProfilRoute
  '/rum': typeof RumRouteWithChildren
  '/statistik': typeof StatistikRouteWithChildren
  '/rum/$roomId': typeof RumRoomIdRoute
  '/statistik/$tab': typeof StatistikTabRoute
  '/katalog/': typeof KatalogIndexRoute
  '/rum/': typeof RumIndexRoute
  '/statistik/': typeof StatistikIndexRoute
  '/katalog/$kind/$typeId': typeof KatalogKindTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/katalog'
    | '/profil'
    | '/rum'
    | '/statistik'
    | '/rum/$roomId'
    | '/statistik/$tab'
    | '/katalog/'
    | '/rum/'
    | '/statistik/'
    | '/katalog/$kind/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/profil'
    | '/rum/$roomId'
    | '/statistik/$tab'
    | '/katalog'
    | '/rum'
    | '/statistik'
    | '/katalog/$kind/$typeId'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/katalog'
    | '/profil'
    | '/rum'
    | '/statistik'
    | '/rum/$roomId'
    | '/statistik/$tab'
    | '/katalog/'
    | '/rum/'
    | '/statistik/'
    | '/katalog/$kind/$typeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  KatalogRoute: typeof KatalogRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  RumRoute: typeof RumRouteWithChildren
  StatistikRoute: typeof StatistikRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum': {
      id: '/rum'
      path: '/rum'
      fullPath: '/rum'
      preLoaderRoute: typeof RumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik/': {
      id: '/statistik/'
      path: '/'
      fullPath: '/statistik/'
      preLoaderRoute: typeof StatistikIndexRouteImport
      parentRoute: typeof StatistikRoute
    }
    '/rum/': {
      id: '/rum/'
      path: '/'
      fullPath: '/rum/'
      preLoaderRoute: typeof RumIndexRouteImport
      parentRoute: typeof RumRoute
    }
    '/katalog/': {
      id: '/katalog/'
      path: '/'
      fullPath: '/katalog/'
      preLoaderRoute: typeof KatalogIndexRouteImport
      parentRoute: typeof KatalogRoute
    }
    '/statistik/$tab': {
      id: '/statistik/$tab'
      path: '/$tab'
      fullPath: '/statistik/$tab'
      preLoaderRoute: typeof StatistikTabRouteImport
      parentRoute: typeof StatistikRoute
    }
    '/rum/$roomId': {
      id: '/rum/$roomId'
      path: '/$roomId'
      fullPath: '/rum/$roomId'
      preLoaderRoute: typeof RumRoomIdRouteImport
      parentRoute: typeof RumRoute
    }
    '/katalog/$kind/$typeId': {
      id: '/katalog/$kind/$typeId'
      path: '/$kind/$typeId'
      fullPath: '/katalog/$kind/$typeId'
      preLoaderRoute: typeof KatalogKindTypeIdRouteImport
      parentRoute: typeof KatalogRoute
    }
  }
}

interface KatalogRouteChildren {
  KatalogIndexRoute: typeof KatalogIndexRoute
  KatalogKindTypeIdRoute: typeof KatalogKindTypeIdRoute
}

const KatalogRouteChildren: KatalogRouteChildren = {
  KatalogIndexRoute: KatalogIndexRoute,
  KatalogKindTypeIdRoute: KatalogKindTypeIdRoute,
}

const KatalogRouteWithChildren =
  KatalogRoute._addFileChildren(KatalogRouteChildren)

interface RumRouteChildren {
  RumRoomIdRoute: typeof RumRoomIdRoute
  RumIndexRoute: typeof RumIndexRoute
}

const RumRouteChildren: RumRouteChildren = {
  RumRoomIdRoute: RumRoomIdRoute,
  RumIndexRoute: RumIndexRoute,
}

const RumRouteWithChildren = RumRoute._addFileChildren(RumRouteChildren)

interface StatistikRouteChildren {
  StatistikTabRoute: typeof StatistikTabRoute
  StatistikIndexRoute: typeof StatistikIndexRoute
}

const StatistikRouteChildren: StatistikRouteChildren = {
  StatistikTabRoute: StatistikTabRoute,
  StatistikIndexRoute: StatistikIndexRoute,
}

const StatistikRouteWithChildren = StatistikRoute._addFileChildren(
  StatistikRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  KatalogRoute: KatalogRouteWithChildren,
  ProfilRoute: ProfilRoute,
  RumRoute: RumRouteWithChildren,
  StatistikRoute: StatistikRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
